openapi: 3.0.0
servers:
  - url: http://localhost:8080/api
info:
  description: Detroit Fasion and Tech Hackathon
  version: 1.0.0
  title: DFTH 2020
paths:
  /order:
    get:
      responses:
        '200':
          description: Retrieve summaries of all orders.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Orders'
      tags:
        - Order
  /order/{orderId}:
    get:
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Retrieve a specific order.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: An order is not found.
      tags:
        - Order
  /order/{orderId}/item/{orderItemId}:
    get:
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
          required: true
        - in: path
          name: orderItemId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Retrieve a specific order item from an order.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/OrderItem'
        '404':
          description: An order item is not found.
      tags:
        - Order Item
components:
  schemas:
    Orders:
      type: object
      required:
        - orders
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
    Order:
      type: object
      required:
        - id
        - orderItems
      properties:
        id:
          type: string
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      required:
        - id
        - productionSteps
      properties:
        id:
          type: string
        productionSteps:
          type: array
          items:
            $ref: '#/components/schemas/ProductionStep'
    ProductionStep:
      type: object
      required:
        - id
        - stepCode
        - title
        - description
        - media
        - status
        - order
      properties:
        id:
          type: string
        stepCode:
          type: string
        title:
          type: string
        description:
          type: string
        media:
          type: array
          items:
            type: string
        status:
          type: string
          enum:
            - not_started
            - in_progress
            - complete
        order:
          type: number
          format: int32
