openapi: 3.0.0
servers:
  - url: http://localhost:8080/api
info:
  description: Detroit Fasion and Tech Hackathon
  version: 1.0.0
  title: DFTH 2020
paths:
  /order:
    get:
      operationId: getOrders
      responses:
        '200':
          description: Retrieve summaries of all orders.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Orders'
      tags:
        - Order
  /order/{orderId}:
    get:
      operationId: getOrder
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Retrieve a specific order.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: An order is not found.
      tags:
        - Order
  /order/{orderId}/item/{orderItemId}:
    get:
      operationId: getOrderItem
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: orderItemId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Retrieve a specific order item from an order.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/OrderItem'
        '404':
          description: An order item is not found.
      tags:
        - Order Item
  /order/{orderId}/item/{orderItemId}/productionStep/{productionStepId}:
    post:
      operationId: updateProductionStep
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: orderItemId
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: productionStepId
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UpdateProductionStep'
      responses:
        '202':
          description: The production step was successfully updated.
        '404':
          description: An order item is not found.
      tags:
        - Production Step
components:
  schemas:
    Orders:
      type: object
      required:
        - orders
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
    Order:
      type: object
      required:
        - id
        - orderItems
      properties:
        id:
          type: string
          format: uuid
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      required:
        - id
        - productionSteps
      properties:
        id:
          type: string
          format: uuid
        productionSteps:
          type: array
          items:
            $ref: '#/components/schemas/ProductionStep'
    ProductionStep:
      type: object
      required:
        - id
        - stepCode
        - title
        - description
        - media
        - status
        - order
      properties:
        id:
          type: string
          format: uuid
        stepCode:
          type: string
        title:
          type: string
        description:
          type: string
        media:
          type: array
          items:
            type: string
        status:
          $ref: '#/components/schemas/ProductionStepStatus'
        order:
          type: number
          format: int32
    ProductionStepStatus:
      type: string
      enum:
        - not_started
        - in_progress
        - complete
    UpdateProductionStep:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/ProductionStepStatus'
