spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:15432/"
    username: postgres
    password: postgres
    initialization-mode: always
server:
  servlet:
    context-path: /api
